version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "[%(asctime)s] %(levelname)s - %(name)s - (%(funcName)s) - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/info.log
        maxBytes: 10485760
        backupCount: 10
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs/errors.log
        maxBytes: 10485760
        backupCount: 10
        encoding: utf8

root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]
